name = "BPDs"
uuid = "23042ae9-e41c-4e47-ad99-03128c974ced"
authors = ["David Anderson <david.ed.anderson@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
BPDsExt = "Plots"

[compat]
Plots = "1.40.13"
Printf = "1.11.0"
